clear; close all;
mask = load('util/mask.mat').masks;

% structure
heart = structure("heart", mask, ["lv" "rv" "lvmy" "rvmy"]);


% global pk param
TR = 3.6;
Nt = 30;

% LV PK PARAMS ------------------
disp("LV stuff")
% - metabolites
pyr = metabolite( ...
    Mz0=0, ...
    R1=1/30, ...
    flips=ones(1,Nt) .* (20 * (pi/180)), ...
    k=[0,0]);

lac = metabolite( ...
    Mz0=0, ...
    R1=1/25, ...
    flips=ones(1,Nt) .* (30 * (pi/180)), ...
    k=[0.0075,0]);

bic = metabolite( ...
    Mz0=0, ...
    R1=1/25, ...
    flips=ones(1,Nt) .* (30 * (pi/180)), ...
    k=[0.0011,0]);

% - input function
Tarrival = 7;
Tbolus = 10;
input_function = realistic_input_function(Nt, TR, Tarrival, Tbolus);

% - put it all into pk_params
lv_pk_params = pk_params(...
    substrate = pyr, ...
    products=[lac, bic], ...
    TR=TR, ...
    input_function=input_function);

% simulate lv metabolite dynamics
lv_met_dynamics = generate_met_dynamics(lv_pk_params);

% plotting
tpts = 1:30;
figure; plot(tpts, lv_met_dynamics(1,:))
hold on
plot(tpts, lv_met_dynamics(2,:))
plot(tpts, lv_met_dynamics(3,:))
hold off




% RV PK PARAMS ----------------
disp("RV stuff")
% metabolites
pyr = metabolite( ...
    Mz0=1, ...
    R1=1/30, ...
    flips=ones(1,Nt) .* (20 * (pi/180)), ...
    k=[0,0]);

lac = metabolite( ...
    Mz0=0, ...
    R1=1/25, ...
    flips=ones(1,Nt) .* (30 * (pi/180)), ...
    k=[0.0045,0]);

bic = metabolite( ...
    Mz0=0, ...
    R1=1/25, ...
    flips=ones(1,Nt) .* (30 * (pi/180)), ...
    k=[0.0005,0]);

% - input function
Tarrival = 0;
Tbolus = 10;
input_function = realistic_input_function(Nt, TR, Tarrival, Tbolus);

% - put it all into pk_params
rv_pk_params = pk_params(...
    substrate = pyr, ...
    products=[lac, bic], ...
    TR=TR, ...
    input_function=input_function);

% simulate lv metabolite dynamics
rv_met_dynamics = generate_met_dynamics(rv_pk_params);

% plotting
tpts = 1:30;
figure; plot(tpts, rv_met_dynamics(1,:))
hold on
plot(tpts, rv_met_dynamics(2,:))
plot(tpts, rv_met_dynamics(3,:))
hold off




% LVMY PK PARAMS ----------------
disp("LVMY stuff")
% metabolites
pyr = metabolite( ...
    Mz0=0, ...
    R1=1/30, ...
    flips=ones(1,Nt) .* (20 * (pi/180)), ...
    k=[0,0]);

lac = metabolite( ...
    Mz0=0, ...
    R1=1/25, ...
    flips=ones(1,Nt) .* (30 * (pi/180)), ...
    k=[0.06,0]);

bic = metabolite( ...
    Mz0=0, ...
    R1=1/25, ...
    flips=ones(1,Nt) .* (30 * (pi/180)), ...
    k=[0.04,0]);

% - input function
Tarrival = 10;
Tbolus = 10;
input_function = realistic_input_function(Nt, TR, Tarrival, Tbolus);

% - put it all into pk_params
lvmy_pk_params = pk_params(...
    substrate = pyr, ...
    products=[lac, bic], ...
    TR=TR, ...
    input_function=input_function);

% simulate lv metabolite dynamics
lvmy_met_dynamics = generate_met_dynamics(lvmy_pk_params);

% plotting
tpts = 1:30;
figure; plot(tpts, lvmy_met_dynamics(1,:))
hold on
plot(tpts, lvmy_met_dynamics(2,:))
plot(tpts, lvmy_met_dynamics(3,:))
hold off




% RVMY PK PARAMS ----------------
disp("LVMY stuff")
% metabolites
pyr = metabolite( ...
    Mz0=0, ...
    R1=1/30, ...
    flips=ones(1,Nt) .* (20 * (pi/180)), ...
    k=[0,0]);

lac = metabolite( ...
    Mz0=0, ...
    R1=1/25, ...
    flips=ones(1,Nt) .* (30 * (pi/180)), ...
    k=[0.02,0]);

bic = metabolite( ...
    Mz0=0, ...
    R1=1/25, ...
    flips=ones(1,Nt) .* (30 * (pi/180)), ...
    k=[0.01,0]);

% - input function
Tarrival = 14;
Tbolus = 10;
input_function = realistic_input_function(Nt, TR, Tarrival, Tbolus);

% - put it all into pk_params
rvmy_pk_params = pk_params(...
    substrate = pyr, ...
    products=[lac, bic], ...
    TR=TR, ...
    input_function=input_function);

% simulate lv metabolite dynamics
rvmy_met_dynamics = pk_model.generate_met_dynamics(rvmy_pk_params);

% plotting
tpts = 1:30;
figure; plot(tpts, rvmy_met_dynamics(1,:))
hold on
plot(tpts, rvmy_met_dynamics(2,:))
plot(tpts, rvmy_met_dynamics(3,:))
hold off

% PK MODEL ------------------
disp("pk model time")
met_dynamics = cat(3, lv_met_dynamics, rv_met_dynamics, lvmy_met_dynamics, rvmy_met_dynamics);
met_dynamics = permute(met_dynamics, [3,1,2]); % = (tissue, met, time_pt)

met_images = pk_model.generate_met_images(heart, met_dynamics);
met_images = squeeze(sum(met_images,4));

% MRI SYSTEM ----------------
disp("mri time")
sample_size = [32 32 11; 16 16 11; 24 24 11];
met_images_mres = mri_system.make_met_images_multires(met_images, sample_size);

SNR = [150 40 20];
met_images_mres = mri_system.add_rician_noise(met_images_mres, SNR);
disp("done")
